#!/bin/sh

. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Init ()
{
	echo -n " xpc-autologin"
}

Config ()
{
    sed -i 's/^AutomaticLogin/#  AutomaticLogin/g' /etc/gdm3/daemon.conf

    # Creating state file
    touch /var/lib/live/config/xpc-autologin
}

Init
Config
